import java.util.Scanner;

/**
 * Story uses the user's input to create a character and ask for information
 * to customize that character. The personal attributes of the character
 * and the choices made within the story will affect the events and ending.
 *
 * @author Mustafa Osmani
 * @version 04/29/2022
 */
public class Story
{
    public static void main(String[] args) {
        Scanner input = new Scanner(System.in);
        Character user = new Character();
        user.setLuck(0);
        System.out.println("Rules: Read text carefully, Make choices, Survive, and leave your mark.");
        System.out.println("");
        System.out.println("Press ENTER to continue the text.");
        enter();
        System.out.println("--------------- VILLAGE ---------------------");
        enter();
        System.out.println("You walk down a muddy path. Rain pours heavily.");
        enter();
        System.out.println("You walk past small wooden homes of villagers.");
        enter();
        System.out.println("Some townsfolk wave at you. You ignore them.");
        enter();
        System.out.println("You reach an open area and notice something.");
        enter();
        System.out.println("To your left, you see a child wearing a merchant's hat. He can probably read and write.");
        enter();
        System.out.println("You need information on the town.");
        enter();
        System.out.println("You walk up to the kid.");
        enter();
        System.out.println("\"Hey, kid. I need directions,\" you ask.");
        enter();
        System.out.println("The kid smiles.");
        enter();
        System.out.println("\"I can help if you give me some coin,\" he says innocently.");
        enter();
        System.out.println("What do you do? (Pay/Threaten/Leave) ");
        String kid = input.next();
        if (kid.toLowerCase().equals("pay")) {
            System.out.println("");
            System.out.println("You toss the kid some coins. He gets excited.");
            enter();
            System.out.println("\"Thank you so much,\" he says with glee.");
            enter();
            user.printLuck(1,"pay the child");
            enter();
            System.out.println("\"Follow me,\" he says.");
            enter();
            System.out.println("He leads you toward something.");
            enter();
            System.out.println("\"The blacksmith here knows everything. He'll help you,\" the kid says.");
            enter();
            System.out.println("The child waves good bye and walks away.");
            enter();
        } else if (kid.toLowerCase().equals("threaten")) {
            System.out.println("");
            System.out.println("You grab the boy by the collar and lift him up, his feet dangling.");
            enter();
            System.out.println("The kid stutters in fear. \"What the heck are you doing?\" ");
            enter();
            System.out.println("\"I could snap you in two if you don't give me something worthwhile,\" you tell him.");
            enter();
            System.out.println("The child points in a direction. \"The blacksmith. He can help. He's in the small house there.\" ");
            enter();
            System.out.println("You drop the kid in the puddle. He gets up and runs away, crying.");
            enter();
            user.printLuck(-1,"threaten a child");
            enter();
            System.out.println("You head where the child pointed to.");
            enter();
        } else if (kid.toLowerCase().equals("leave")) {
            System.out.println("");
            System.out.println("You walk away.");
            enter();
            System.out.println("\"Wait, where are you going?,\" the child says in confusion.");
            enter();
            System.out.println("\"I can help! Come on, man! I need money!\" ");
            enter();
            System.out.println("You ignore him and keep walking.");
            enter();
            System.out.println("---------------- 2 HOURS LATER ------------------");
            System.out.println("");
            System.out.println("After asking around for some time, you find out that the blacksmith is knowledgeable.");
            enter();
            System.out.println("You head towards the blacksmith's direction.");
            enter();
        }
        System.out.println("You see a small wooden shelter.");
        enter();
        System.out.println("You notice a sign that reads BLACKSMITH.");
        enter();
        System.out.println("You see that you aren't in the best state and need some upgrades.");
        enter();
        System.out.println("Do you enter? (Yes/No) ");
        String an = input.next();
        String real = an.toLowerCase();
        if (real.equals("yes")) {
            System.out.println("");
            System.out.println("You enter the shop.");
            enter();
        } else {
            System.out.println("");
            System.out.println("You start walking away from the shop.");
            enter();
            System.out.println("Suddenly, the shop's door opens. A man comes out.");
            enter();
            System.out.println("He says, \"You look like you need some gear. Come in. I don't bite.\" ");
            enter();
            System.out.println("You enter the shop.");
            enter();
        }
        System.out.println("-------------- BLACKSMITH SHOP ------------------");
        System.out.println("");
        System.out.println("The inside of the shop is dim with the smell of coal and fire.");
        enter();
        System.out.println("The blacksmith smiles. \"You got a name?\", he says.");
        enter();
        System.out.println("The man seems harmless. You trust him enough to say it.");
        System.out.println("");
        System.out.print("ENTER YOUR NAME: ");
        String title = input.next();
        user.setName(title);
        String n = user.getName();
        System.out.println("");
        System.out.println(n + "? That's a strange one, but it sounds familier.");
        enter();
        System.out.println("Well, whatever. So, what is your class? Gotta know what I'm working with.");
        System.out.println("");
        System.out.println("MAGE, SWORDSMAN, or HEALER? ");
        String c = input.next();
        String clas = c.toLowerCase();
        if (clas.equals("mage")) {
            user.setHeroClass(HeroClass.MAGE);
            System.out.println("");
            System.out.println("The man laughs. \"A magic user, I see. I wonder how many folk you've made disappear.\" ");
            enter();
        } else if (clas.equals("swordsman")) {
            user.setHeroClass(HeroClass.SWORDSMAN);
            System.out.println("");
            System.out.println("The man laughs. \"Of course. I bet you've sliced down many with that fine piece of steel.\" ");
            enter();
        } else if (clas.equals("healer")) {
            user.setHeroClass(HeroClass.HEALER);
            System.out.println("");
            System.out.println("The man laughs. \"No offense, but you're the most dangerous-looking healer I've seen.\" ");
            enter();
        }
        System.out.println("You are used to these type of comments. Fear and death is commonly associated with you.");
        enter();
        System.out.println("You've grown numb to it.");
        enter();
        System.out.println("The blacksmith gets to work on your weapon and armor.");
        enter();
        System.out.println("You explore the shop to pass time.");
        enter();
        System.out.println("On a table, you notice a necklace with a white stone as a pendant.");
        enter();
        System.out.println("It looks valuable, but it's displayed beside other weapons.");
        enter();
        System.out.println("It could be dangerous. You look over at the blacksmith. He's distracted.");
        enter();
        
        //necklace
        System.out.print("ASK about the necklace? STEAL the necklace? Or IGNORE it?");
        System.out.println("");
        System.out.print("CHOOSE: ");
        String asi = input.next(); 
        if (asi.toLowerCase().equals("ask")) {
            System.out.println("");
            user.printLuck(1, "not steal");
            enter();
            System.out.println("You ask the man, \"What is this necklace?,\" as you pick it up.");
            enter();
            System.out.println("\"Be careful!,\" he screams. \"It's a flash bomb!\" ");
            enter();
            System.out.println("You put it down and step away.");
            enter();
        } else if (asi.toLowerCase().equals("steal")) {
            System.out.println("");
            System.out.println("You glance over at the man one more time. It's safe to steal.");
            enter();
            System.out.println("You swipe it successfully.");
            enter();
            user.addItem("necklace");
            enter();
            user.printLuck(-1, "steal");
            enter();
        } else if (asi.toLowerCase().equals("ignore")) {
            System.out.println("");
            System.out.println("You step away from it.");
            enter();
            user.printLuck(1, "not steal");
            enter();
        }
        System.out.println("The man notices your stoic look and smiles.");
        enter();
        System.out.println("\"I noticed a small injury on your arm when you walked in. Is it from the beasts?\" ");
        enter();
        
        //HEALTH POTION
        System.out.println("The man pulls out a Health Potion. He offers it to you.");
        enter();
        user.setHealth(80);
        user.printHealth();
        enter();
        System.out.println("Do you take it? (Yes/No) ");
        String ti = input.next();
        String boost = ti.toLowerCase();
        System.out.println("");
        if (boost.equals("yes")) {
            user.setHealth(100);
            System.out.println("You chug the health potion.");
            enter();
            user.printHealth();
            enter();
            System.out.println("You thank the man. He shakes his head. \"It's your first time here. Gotta leave an impression.");
            enter();
        } else {
            user.setHealth(80);
            System.out.println("The man looks upset. \"It was your first time here. Wanted to leave an impression.\" ");
            enter();
        }
        System.out.println("After a bit of time, the blacksmith is done. He hands you the goods.");
        enter();
        if (user.getHeroClass().equals(HeroClass.MAGE)) {
            System.out.println("\"A Magical Staff for the Mage,\" he says.");
            enter();
        } else if (user.getHeroClass().equals(HeroClass.SWORDSMAN)) {
            System.out.println("\"A Steel Blade for the Swordsman,\" he says.");
            enter();
        } else if (user.getHeroClass().equals(HeroClass.HEALER)) {
            System.out.println("\"An Enchanted Book of Recovery for the Healer,\" he says.");
            enter();
        }
        System.out.println("You take it from him and inspect it. It's high-quality.");
        enter();
        System.out.println("You toss him some coins and head out.");
        enter();
        System.out.println("The blacksmith smiles. \"If you ever want to come back, I'm here.\" ");
        enter();
        System.out.println("His kindness doesn't faze you.");
        enter();
        System.out.println("You open the door and FIFTEEN men stand outside.");
        enter();
        System.out.println("They all wear black armor with two red stripes on their arms.");
        enter();
        System.out.println("The blacksmith sees the men outside and gasps. \"Cleaners!\" ");
        enter();
        System.out.println("The blacksmith stands in front of you, defending you.");
        enter();
        System.out.println("\"We don't want trouble!\", he yells at the men.");
        enter();
        System.out.println("They stare with stern looks, unfazed.");
        enter();
        System.out.println("You walk in front of the blacksmith and walk into the crowd.");
        enter();
        System.out.println("The blacksmith yells at you. \"Stay back " + n + "! Those men are known criminals!\" ");
        enter();
        System.out.println("You raise a hand and tell the men to head north. They begin to walk, following your command. You lead them.");
        enter();
        System.out.println("The blacksmith is shocked. He realizes.");
        enter();
        if (user.getHeroClass().equals(HeroClass.MAGE)) {
            System.out.println("You...You're " + n + "! The Mage of Blood and Lightning!");
            enter();
            System.out.println("Your lightning has caused many towns to evacuate! You've striked many down for sport!");
            enter();
            System.out.println("\"For money,\" you correct him.");
            enter();
        } else if (user.getHeroClass().equals(HeroClass.SWORDSMAN)) {
            System.out.println("You...You're " + n + "! The Butcher of 100 Bodies!");
            enter();
            System.out.println("You've slain people for sport!");
            enter();
            System.out.println("\"For money,\" you correct him.");
            enter();
        } else if (user.getHeroClass().equals(HeroClass.HEALER)) {
            System.out.println("You...You're " + n + "! The Devil's Ressurector!");
            enter();
            System.out.println("You've ressurected slain monsters and caused havoc in towns. Many have died, because of you! And, you do it for sport!");
            enter();
            System.out.println("\"For money,\" you correct him.");
            enter();
        }
        System.out.println("The man is disgusted. He realizes your reputation.");
        enter();
        if (asi.toLowerCase().equals("steal")) {
            System.out.println("\"I saw you steal my necklace earlier. I wanted to give you a chance, so I didn't confront you,\" he says.");
            enter();
            System.out.println("\"You're a criminal!\" ");
            enter();
        }
        System.out.println("Get away from my shop! Never come back you monsters!");
        enter();
        System.out.println("He slams his door shut. You and your men walk away, unfazed.");
        enter();
        
        //CHAPTER TWO
        System.out.println("--------------- VILLAGE ---------------------");
        enter();
        System.out.println("You and your men start heading out of town. The citizens watch you and your men in fear and anger.");
        enter();
        System.out.println("Your reputation is not that good.");
        enter();
        System.out.println("As you head out of town, you notice the boy with the merchant hat in the crowd.");
        enter();
        if (kid.toLowerCase().equals("pay")) {
            System.out.println("He stares at you with sadness. Everyone's attitude toward you upsets him.");
            enter();
            System.out.println("You aren't used to pity, so it strikes a nerve with you.");
            enter();
        } else if (kid.toLowerCase().equals("threaten")) {
            System.out.println("He stares at you with anger, holding the collar that you pulled. You feel unfazed, but something's different.");
            enter();
            System.out.println("You see a tear fall from the kid's face. A look of pity. For you?");
            enter();
            System.out.println("That look strikes a nerve with you.");
            enter();
        } else if (kid.toLowerCase().equals("leave")) {
            System.out.println("He stares at you in confusion. Not sure of why others are hostile towards you.");
            enter();
            System.out.println("Suddenly, he waves at you innocently. A look of sadnss on his face.");
            enter();
            System.out.println("You aren't used to pity, so it strikes a nerve with you.");
            enter();
        }
        System.out.println("------------------ OUTSKIRTS ---------------------");
        enter();
        System.out.println("You reach the outskirts of the area.");
        enter();
        System.out.println("It's a high hill that has a view of the town. You look back once more.");
        enter();
        System.out.println("Your men look tired and frustrated.");
        enter();
        Character millard = new Character("Millard", 100, HeroClass.MAGE, 50);
        System.out.println("\"Excuse me,\" ");
        enter();
        System.out.println("You turn around and see a man. He wears torn rags and is covered in dirt. He holds a Staff.");
        enter();
        System.out.println("Your men become defensive, sensing an evil aura from him.");
        enter();
        System.out.println("\"Do not be alarmed,\" he says.");
        enter();
        System.out.println("\"I've come with a proposition.\" ");
        enter();
        System.out.println("He seems untrustworthy. But you continue to listen.");
        enter();
        System.out.println("\"Go on,\" you tell him.");
        enter();
        System.out.println("He smiles. \"I need an army. A strong one at that.\" ");
        enter();
        System.out.println("\"I've heard things about you and your men. Wonderful things. The amount of pain and suffering you've caused. All of it.\" ");
        enter();
        System.out.println("\"If you join me, I'll give you a life of power and respect.\" ");
        enter();
        System.out.println("\"All your wishes and dreams can come true. All you need to do is say yes and the contract is complete.\" ");
        enter();
        System.out.println("\"A contract,\" you think to yourself.");
        enter();
        System.out.println("\"You're a mage,\" you tell the mysterious man.");
        enter();
        System.out.println("He smiles and bows.");
        enter();
        System.out.println("\"Millard.\" ");
        enter();
        System.out.println("Your men gasp. It's Millard. The Mage of Poisons and Sacrifice.");
        enter();
        System.out.println("He's extremely cruel and dangerous. He has a reputation far worse than yours.");
        enter();
        System.out.println("He's also extremely powerful.");
        enter();
        System.out.println("\"So, what do you say?\" he says.");
        enter();
        System.out.println("\"What is your goal?,\" you ask him.");
        enter();
        System.out.println("\"I need sacrifices to ressurect the Demon Lord,\" he says.");
        enter();
        System.out.println("Your men become worried, but they are still listening.");
        enter();
        System.out.println("\"That small town would be perfect as an offering.\" ");
        enter();
        System.out.println("\"So, what do you say?\" ");
        enter();
        System.out.println("You wonder.");
        enter();
        System.out.println("\"Join me or no?\" (Join/Decline) ");
        String mill = input.next();
        if (mill.toLowerCase().equals("join")) {
            System.out.println("");
            System.out.println("The man smiles. \"Approach me,\" he says confidently.");
            enter();
            System.out.println("You and your men come closer. He lifts his Staff and slams it on the ground.");
            enter();
            System.out.println("The clouds open up, revealing a black hole.");
            enter();
            System.out.println("Black smoke surrounds you and your men. You see your body transforming.");
            enter();
            System.out.println("Some men gain more arms, some grow more eyes, and some become larger.");
            enter();
            System.out.println("You feel stronger than ever.");
            enter();
            System.out.println("Your men look up at you, a giant compared to before.");
            enter();
            System.out.println("You have become the beast all fear.");
            enter();
            user.setHealth(10000);
            user.printHealth();
            enter();
            System.out.println("------------------ VILLAGE ---------------------");
            enter();
            System.out.println("The townsfolk see something in the distance.");
            enter();
            System.out.println("A large group of monsters run toward the village.");
            enter();
            System.out.println("People scream as they trample over one another.");
            enter();
            System.out.println("One monster is quicker than the others. He reaches the town first and claws through people.");
            enter();
            System.out.println("Other monsters follow suit. One monster throws rocks, destroying the homes and shops.");
            enter();
            System.out.println("The blacksmith holds a sword, slicing through some of the monsters.");
            enter();
            System.out.println("He, eventually, becomes overwhelmed by the number of monsters and is defeated.");
            enter();
            System.out.println("The town is in ruins as you watch on the hill.");
            enter();
            System.out.println("Millard smiles at you. \"We will rule all in no time " + n + ". Don't worry.\" he says.");
            enter();
            System.out.println("You see your reflection in the rain puddle beside you.");
            enter();
            System.out.println("An unrecognizable creature looks back. You wonder if your choice was the right one.");
            enter();
            System.out.println("Everyone rejected you. Everyone despised you. It was the only way...right?");
            enter();
            System.out.println("Suddenly, you see something in the center of the ruined town.");
            enter();
            System.out.println("Your change has given you improved vision and strength.");
            enter();
            System.out.println("In the middle of the flames and bloodbath, a merchant's hat rests on the floor."); 
            enter();
            user.printAwards(1,"");
        } else if (mill.toLowerCase().equals("decline")) {
            System.out.println("");
            System.out.println("You look at Millard, who is smiling.");
            enter();
            System.out.println("You remember the kid with the merchant hat. His look of sadness.");
            enter();
            System.out.println("\"Nah, I think we're fine.\" you tell him.");
            enter();
            System.out.println("Your men were indecisive, but your choice makes them agree with you.");
            enter();
            user.printLuck(1,"not side with evil");
            enter();
            System.out.println("\"I've heard of you, Millard. You turn people into beasts without reason,\" you say.");
            enter();
            System.out.println("\"We like our bodies just the way they are. And the townsfolk aren't that bad.\" ");
            enter();
            System.out.println("Millard smiles, not saying a word.");
            enter();
            System.out.println("It's an intense stare-down.");
            enter();
            System.out.println("Suddenly, Millard laughs.");
            enter();
            System.out.println("\"Fine by me,\" he says.");
            enter();
            System.out.println("Suddenly, he lifts his Staff.");
            enter();
            System.out.println("He slams it down and green smoke flies everywhere.");
            enter();
            System.out.println("You and your men inhale it.");
            enter();
            System.out.println("You and your men feel fine.");
            enter();
            System.out.println("Suddenly, you and your men feel intense pain in your bodies.");
            enter();
            System.out.println("It's poison!");
            enter();
            user.EnemyDamage(50,"Millard","poisoned");
            enter();
            user.printHealth();
            enter();
            System.out.println("\"Do you change your mind?,\" Millard says.");
            enter();
            System.out.println("The pain is unbearable, but you resist.");
            enter();
            System.out.println("But your men can't handle it. One by one, they submit.");
            enter();
            System.out.println("Millard laughs and snaps his finger.");
            enter();
            System.out.println("Your men transform into terrifying monsters that can't control themselves.");
            enter();
            System.out.println("They surround you.");
            enter();
            System.out.println("\"These men need their leader, " + n + ",\" Millard says.");
            enter();
            System.out.println("\"Join me.\" ");
            enter();
            if (user.getHeroClass().equals(HeroClass.MAGE)) {
                System.out.println("You reach for your Staff.");
                enter();
                System.out.println("Millard picks it up before you.");
                enter();
                System.out.println("\"So, you're a Mage. Just like me.\" he says.");
                enter();
                System.out.println("You feel another wave of pain.");
                enter();
                user.EnemyDamage(40,"Millard","poisoned");
                enter();
                user.printHealth();
                enter();
            } else if (user.getHeroClass().equals(HeroClass.SWORDSMAN)) {
                System.out.println("You reach for your sword.");
                enter();
                System.out.println(n + ". The Butcher of 100 Bodies. I thought that title meant you were strong. I was mistaken,\" Millard says.");
                enter();
                System.out.println("You're a failure of a Swordsman, " + n + ".");
                enter();
                System.out.println("You feel another wave of pain.");
                enter();
                user.EnemyDamage(40,"Millard","poisoned");
                enter();
                user.printHealth();
                enter();
            } else if (user.getHeroClass().equals(HeroClass.HEALER)) {
                System.out.println("You reach for the Enchanted Book of Recovery.");
                enter();
                System.out.println("\"I've heard about you, " + n + ".\" ");
                enter();
                System.out.println("\"You're a second-class healer. A nobody.\" ");
                enter();
                System.out.println("\"Your friends are dying and you can't do the one thing you could do. Heal them.\" ");
                enter();
                System.out.println("You feel another wave of pain.");
                enter();
                user.EnemyDamage(40,"Millard","poisoned");
                enter();
                user.printHealth();
                enter();
            }
            System.out.println("Millard stands over you.");
            enter();
            System.out.println("\"Change your mind yet?\" he says.");
            enter();
            System.out.println("He sees you struggling and sighs. He pulls out a Health Potion.");
            enter();
            System.out.println("He pours a generous amount in your mouth.");
            enter();
            user.setHealth(90);
            user.printHealth();
            enter();
            System.out.println("\"See? I'm nice,\" Millard says.");
            enter();
            System.out.println("\"Now, your answer.\" ");
            enter();
            System.out.println("\"Do you join me?\" (Lie/No)");
            String join = input.next();
            if (join.toLowerCase().equals("lie")) {
                System.out.println("");
                System.out.println("\"Yes,\" you say.");
                enter();
                System.out.println("Millard laughs.");
                enter();
                System.out.println("\"You're lying.\" ");
                enter();
                join = "no";
            }
            int attackPoint = 0;
            while (join.toLowerCase().equals("no") || join.toLowerCase().equals("attack")) {
                user.EnemyDamage(30,"A Monster","clawed");
                enter();
                if (attackPoint == 1) {
                    System.out.println("As Millard's foot is on your hand, you notice that he's wearing sandals.");
                    enter();
                    System.out.println("You see a sharp rock beside it, too.");
                    enter();
                    System.out.println("You need to be quick.");
                    enter();
                    System.out.println("Millard looks away for a second and you grab the rock and drive it into his foot.");
                    enter();
                    System.out.println("Millard screams.");
                    enter();
                    user.printLuck(1,"attack Millard");
                    enter();
                    break;
                }
                if (user.getHealth() <= 15) {
                    break;
                }
                user.printHealth();
                enter();
                user.printLuck(1,"resist again");
                enter();
                System.out.println("\"We can be here all day,\" Millard says.");
                enter();
                System.out.println("\"Will you join me?\" (Attack/No)");
                join = input.next();
                if (join.toLowerCase().equals("attack")) {
                    attackPoint +=1;
                    System.out.println("");
                    System.out.println("You try hitting Millard, but he steps on your hand.");
                    enter();
                }
            }
            //attack
            if (attackPoint == 1) {
                System.out.println("Millard grabs his foot in agony.");
                enter();
                System.out.println("\"Kill that bastard!,\" he yells.");
                enter();
                System.out.println("The monsters turn to you and charge.");
                enter();
            } else {
                System.out.println("Millard sees your resistance and smiles.");
                enter();
                System.out.println("\"I respect your strong will, " + n + ".\" he says.");
                enter();
                System.out.println("\"If only your men had the same strength. Instead, they're weak bastards.\" ");
                enter();
                System.out.println("He laughs as the monsters approach you.");
                enter();
                System.out.println("\"Kill him,\" Millard says.");
                enter();
                System.out.println("The monsters turn to you and charge.");
                enter();
            }
            //necklace route
            if (user.hasItem("necklace")) {
                System.out.println("You feel something in your pocket. It's the necklace you stole.");
                enter();
                System.out.println("Millard doesn't notice you reaching for it.");
                enter();
                System.out.println("You pull it out quickly and slam it on the floor, closing your eyes.");
                enter();
                System.out.println("A bright light beams out and bursts. You feel a boost in power.");
                enter();
                System.out.println("Everyone is blinded, including Millard.");
                enter();
                System.out.println("You get up and see Millard holding his eyes. He's open to a hit. You also see his Staff.");
                enter();
                System.out.println("Kill Millard or Break his Staff? (Kill/Break) ");
                String kb = input.next();
                if (kb.toLowerCase().equals("kill")) {
                    System.out.println("");
                    System.out.println("You sprint toward Millard.");
                    enter();
                    if (user.getHeroClass().equals(HeroClass.MAGE)) {
                    System.out.println("You lift your Staff and use your magic.");
                    enter();
                    System.out.println("Millard opens one eye and sees your aura.");
                    enter();
                    System.out.println("He laughs.");
                    enter();
                    System.out.println("\"Well played, " + n + ". A true Mage.\" ");
                    enter();
                    System.out.println("You scream at the top of your lungs. \"LIGHTNING!\" ");
                    enter();
                    System.out.println("Lightning strikes down onto Millard and the monsters, charring them.");
                    enter();
                    System.out.println("Millard stands still for a second, then falls to the floor.");
                    enter();
                    System.out.println("The monsters fall, too.");
                    enter();
                    System.out.println("Every enemy turns to dust. The wind blows them away.");
                    enter();
                    millard.setHealth(0);
                    millard.printHealth();
                    enter();
                    System.out.println("You sit on the ground, tired.");
                    enter();
                    System.out.println("The poison is still in effect.");
                    enter();
                    System.out.println("You see the Millard's Staff and try to grab it.");
                    enter();
                    System.out.println("But you're too tired.");
                    enter();
                    System.out.println("You know that you're dying.");
                    enter();
                    user.setHealth(32);
                    user.printHealth();
                    enter();
                    System.out.println("You remember everyone in the town's face. Their looks of anger toward you.");
                    enter();
                    user.setHealth(21);
                    user.printHealth();
                    enter();
                    System.out.println("You remember the boy with the merchant hat. The look of sadness.");
                    enter();
                    user.setHealth(9);
                    user.printHealth();
                    enter();
                    System.out.println("You remember your sins in life.");
                    enter();
                    System.out.println("But you saved this town and it's people.");
                    enter();
                    System.out.println("Is it enough? Did you do enough?");
                    enter();
                    user.setHealth(1);
                    user.printHealth();
                    enter();
                    System.out.println("That's all you can hope for.");
                    enter();
                    user.setHealth(0);
                    user.printHealth();
                    enter();
                    System.out.println("The town is at peace, unaware of how close their end was.");
                    enter();
                    System.out.println("The boy in the merchant hat has a feeling and looks up at the hill in the distance.");
                    enter();
                    System.out.println("He stares at it for a second, but shrugs it off. Must be nothing.");
                    enter();
                    user.printAwards(2,"");
                    } else if (user.getHeroClass().equals(HeroClass.SWORDSMAN)) {
                    System.out.println("You lift your Sword high and proud.");
                    enter();
                    System.out.println("Millard opens one eye and sees your aura.");
                    enter();
                    System.out.println("He laughs.");
                    enter();
                    System.out.println("\"Well played, " + n + ". A true Swordsman.\" ");
                    enter();
                    System.out.println("You scream at the top of your lungs.");
                    enter();
                    System.out.println("You swing your Sword horizontally.");
                    enter();
                    System.out.println("A red line follows your Sword.");
                    enter();
                    System.out.println("Every monster stands still. Millard is still, too.");
                    enter();
                    System.out.println("Suddenly, they all fall over with their top halves disconnecting.");
                    enter();
                    millard.setHealth(0);
                    millard.printHealth();
                    enter();
                    System.out.println("You sit on the ground, tired.");
                    enter();
                    System.out.println("The poison is still in effect.");
                    enter();
                    System.out.println("You see the Millard's Staff and try to grab it.");
                    enter();
                    System.out.println("But you're too tired.");
                    enter();
                    System.out.println("You know that you're dying.");
                    enter();
                    user.setHealth(32);
                    user.printHealth();
                    enter();
                    System.out.println("You remember everyone in the town's face. Their looks of anger toward you.");
                    enter();
                    user.setHealth(21);
                    user.printHealth();
                    enter();
                    System.out.println("You remember the boy with the merchant hat. The look of sadness.");
                    enter();
                    user.setHealth(9);
                    user.printHealth();
                    enter();
                    System.out.println("You remember your sins in life.");
                    enter();
                    System.out.println("But you saved this town and it's people.");
                    enter();
                    System.out.println("Is it enough? Did you do enough?");
                    enter();
                    user.setHealth(1);
                    user.printHealth();
                    enter();
                    System.out.println("That's all you can hope for.");
                    enter();
                    user.setHealth(0);
                    user.printHealth();
                    enter();
                    System.out.println("The town is at peace, unaware of how close their end was.");
                    enter();
                    System.out.println("The boy in the merchant hat has a feeling and looks up at the hill in the distance.");
                    enter();
                    System.out.println("He stares at it for a second, but shrugs it off. Must be nothing.");
                    enter();
                    user.printAwards(2,"");
                    } else if (user.getHeroClass().equals(HeroClass.HEALER)) {
                    System.out.println("You open your Book of Recovery.");
                    enter();
                    System.out.println("Millard opens one eye and sees your aura.");
                    enter();
                    System.out.println("He laughs.");
                    enter();
                    System.out.println("\"Well played, " + n + ". A true Healer.\" ");
                    enter();
                    System.out.println("You scream the ultimate spell at the top of your lungs. \"HEAL THE WORLD!\" ");
                    enter();
                    System.out.println("Magic light swarms around you and travels to every monster.");
                    enter();
                    System.out.println("They turn back into humans and all the evil magic leaves their body.");
                    enter();
                    System.out.println("The dark magic swarms into a mist and flies toward it's host, Millard.");
                    enter();
                    System.out.println("It flies into his body at once. A human cannot handle it, so Millard turns pale.");
                    enter();
                    System.out.println("The last thing everyone hears is Millard laughing.");
                    enter();
                    System.out.println("When the magic disperses, everyone sees Millard. A skeleton of his former self.");
                    enter();
                    System.out.println("He falls to the ground, turning into dust.");
                    enter();
                    millard.setHealth(0);
                    millard.printHealth();
                    enter();
                    System.out.println("You sit on the ground, tired.");
                    enter();
                    System.out.println("The poison is still in effect.");
                    enter();
                    System.out.println("You see the Millard's Staff and try to grab it.");
                    enter();
                    System.out.println("One of your men grab it and break it. The poison stops.");
                    enter();
                    System.out.println("You're still tired. You realize that the spell, HEAL THE WORLD, takes your life to heal others.");
                    enter();
                    System.out.println("That is the condition.");
                    enter();
                    System.out.println("You know that you're dying.");
                    enter();
                    System.out.println("Your men surround you, thanking you for saving them.");
                    enter();
                    System.out.println("Some of them cry, while others try to call for help.");
                    enter();
                    System.out.println("You smile, realizing that you were wanted in this world.");
                    enter();
                    user.setHealth(32);
                    user.printHealth();
                    enter();
                    System.out.println("You remember everyone in the town's face. Their looks of anger toward you.");
                    enter();
                    user.setHealth(21);
                    user.printHealth();
                    enter();
                    System.out.println("You remember the boy with the merchant hat. The look of sadness.");
                    enter();
                    user.setHealth(9);
                    user.printHealth();
                    enter();
                    System.out.println("You remember your sins in life.");
                    enter();
                    System.out.println("But you saved this town and it's people.");
                    enter();
                    System.out.println("Is it enough? Did you do enough?");
                    enter();
                    user.setHealth(1);
                    user.printHealth();
                    enter();
                    System.out.println("That's all you can hope for.");
                    enter();
                    user.setHealth(0);
                    user.printHealth();
                    enter();
                    System.out.println("The town is at peace, unaware of how close their end was.");
                    enter();
                    System.out.println("The boy in the merchant hat has a feeling and looks up at the hill in the distance.");
                    enter();
                    System.out.println("He stares at it for a second, but shrugs it off. Must be nothing.");
                    enter();
                    user.printAwards(2,"");
                    }
                } else {
                    System.out.println("");
                    System.out.println("You sprint toward Millard.");
                    enter();
                    System.out.println("You grab his Staff and, without hesitation, snap it in two.");
                    enter();
                    System.out.println("You feel the poison slowly wearing off.");
                    enter();
                    user.setHealth(2);
                    user.printHealth();
                    enter();
                }
            }
            System.out.println("The monsters are seconds away from reaching you.");
            enter();
            System.out.println("You feel cornered.");
            enter();
            System.out.println("Suddenly, a distant arrow flies past you.");
            enter();
            System.out.println("It hits Millard in the arm.");
            enter();
            System.out.println("\"What the hell!,\" Millard yells.");
            enter();
            System.out.println("You turn around in confusion and see none other than the Blacksmith!");
            enter();
            System.out.println("\"It's you!,\" you scream.");
            enter();
            System.out.println("Hello, " + n + ".");
            enter();
            System.out.println("The monsters scream and roar at the Blacksmith.");
            enter();
            System.out.println("The Blacksmith is unfazed. The monsters run up to him, but are stopped by a shot of flames.");
            enter();
            System.out.println("They jump back to avoid burning.");
            enter();
            System.out.println("Behind the Blacksmith are the other townsfolk. They stand together holding weapons. Some hold, bows, some hold swords, and others hold staffs.");
            enter();
            System.out.println("\"You really thought I came alone?,\" the Blacksmith says.");
            enter();
            System.out.println("You're confused. How did they know?");
            enter();
            System.out.println("\"We wanted you and your men gone. But, someone talked us out of it,\" the Blacksmith says.");
            enter();
            System.out.println("From behind the Blacksmith, the boy with the merchant hat walks forward.");
            enter();
            System.out.println("\"Apparently, the boy followed you and your men to this hill to speak to you. He saw your confrontation with this mad man.\" ");
            enter();
            System.out.println("\"He also saw how you and your men tried protecting us.\" ");
            enter();
            System.out.println("The townsfolk smile.");
            enter();
            System.out.println("This is a new feeling. You feel somewhat...relieved.");
            enter();
            System.out.println("Millard grits his teeth. \"This means nothing!\" he says.");
            enter();
            System.out.println("Millard lifts his Staff and aims it at the townsfolk.");
            enter();
            System.out.println("The monsters growl and hiss at everyone.");
            enter();
            System.out.println("You can barely stand. Suddenly, you feel someone grab your shoulder.");
            enter();
            System.out.println("You see the Blacksmith holding a Health Potion. \"Take it,\" he says.");
            enter();
            System.out.println("You take it and chug the entire thing. You feel strength slowly coming back.");
            enter();
            user.setHealth(100);
            user.printHealth();
            enter();
            if (user.getHeroClass().equals(HeroClass.MAGE)) {
                System.out.println("You pick up your Staff.");
                enter();
                System.out.println("\"Hope my creation's to your liking,\" the Blacksmith says.");
                enter();
                System.out.println("\"We'll see,\" you say.");
                enter();
            } else if (user.getHeroClass().equals(HeroClass.SWORDSMAN)) {
                System.out.println("\"You pick up your Sword.");
                enter();
                System.out.println("\"Hope my creation's to your liking,\" the Blacksmith says.");
                enter();
                System.out.println("\"We'll see,\" you say.");
                enter();
            } else if (user.getHeroClass().equals(HeroClass.HEALER)) {
                System.out.println("You pick up your Book of Recovery.");
                enter();
                System.out.println("\"Hope my creation's to your liking,\" the Blacksmith says.");
                enter();
                System.out.println("\"We'll see,\" you say.");
                enter();
            }
            System.out.println("Millard laughs. \"Come on, then. Let's get to it!\" ");
            enter();
            System.out.println("Everyone stares for a moment.");
            enter();
            System.out.println("\"We're ready when you are, " + n + ".\" ");
            enter();
            System.out.println("\"When you say CHARGE, we'll go.\" ");
            enter();
            System.out.println("You look at Millard. He stares at you with anger. You smile.");
            enter();
            System.out.println("Say it, Hero: ");
            String charge = input.next();
            System.out.println("");
            System.out.println("Everyone yells and runs toward Millard, weapons in hand.");
            enter();
            System.out.println("Millard commands the monsters to charge at you.");
            enter();
            System.out.println("You, suddenly, remember that these monsters were your friends.");
            enter();
            System.out.println("There could be a way to bring them back.");
            enter();
            if (user.getHeroClass().equals(HeroClass.HEALER)) {
                System.out.println("You look in your Book of Recovery and see an ultimate spell.");
                enter();
                System.out.println("It's called HEAL THE WORLD and it takes spells off any subject, but the negative is that it takes a toll on the user, causing death.");
                enter();
                System.out.println("You have two choices.");
                enter();
            }
            System.out.println("KILL the monsters or RISK saving them? (Kill/Risk) ");
            String kr = input.next();
            if (kr.toLowerCase().equals("kill")) {
                System.out.println("");
                System.out.println("You realize that your friends are already gone. It's too risky to try talking to them.");
                enter();
                System.out.println("You watch as the townsfolk kill the monsters.");
                enter();
                System.out.println("You remember memories with your friends.");
                enter();
                System.out.println("But it's okay. They would understand.");
                enter();
                System.out.println("You kill every monster in your path with tears in your eyes.");
                enter();
                System.out.println("Finally, you see Millard. He panics and uses his magic to command the final beast.");
                enter();
                System.out.println("It grows wings, including the dead monsters, and Millard hops on.");
                enter();
                System.out.println("\"We'll meet again, " + n + "!\" ");
                enter();
                System.out.println("He flies away laughing.");
                enter();
                System.out.println("\"We can't let him get away!,\" the boy in the merchant hat says.");
                enter();
                if (user.getHeroClass().equals(HeroClass.HEALER)) {
                        System.out.println("You quickly open your Book of Recovery and find a page of TEMPORARY REVIVAL.");
                        enter();
                        System.out.println("You approach one of the dead monsters with wings.");
                        enter();
                        System.out.println("You start chanting. You begin to glow. The monster begins to glow.");
                        enter();
                        System.out.println("\"Are you reviving it?,\" the Blacksmith asks.");
                        enter();
                        System.out.println("You nod your head. \"Just wait,\" you say.");
                        enter();
                        System.out.println("Suddenly, the monster opens it's eyes. Everyone takes a step back, except you.");
                        enter();
                        System.out.println("The monster gets up and looks at you. It has no anger, no malice, nothing.");
                        enter();
                        System.out.println("It sees your face and...recognizes it.");
                        enter();
                        System.out.println("You smile at it. \"I'm sorry I couldn't save you,\" you say.");
                        enter();
                        System.out.println("It lowers it's head. You point at Millard.");
                        enter();
                        System.out.println("It looks at Millard and understands the task.");
                        enter();
                        System.out.println("It looks at you one more time before it flies away.");
                        enter();
                        System.out.println("Millard laughs as he stares at the sky. \"What an experience!,\" he says.");
                        enter();
                        System.out.println("\"I will come back stronger than ever. Then, I can kill them. Kill them all!\" ");
                        enter();
                        System.out.println("Millard laughs, but he hears something.");
                        enter();
                        System.out.println("He turns around...and sees a huge monster.");
                        enter();
                        System.out.println("\"WHAT THE-\" ");
                        enter();
                        System.out.println("The monster bites down.");
                        enter();
                        millard.setHealth(0);
                        millard.printHealth();
                        enter();
                } else if (user.getHeroClass().equals(HeroClass.MAGE)) {
                    System.out.println("You lift your Staff and hold it tightly.");
                    enter();
                    System.out.println("Everyone is quiet.");
                    enter();
                    System.out.println("You begin to glow. Dark clouds begin to form.");
                    enter();
                    System.out.println("You look at Millard's direction...and point your Staff.");
                    enter();
                    System.out.println("Millard laughs as he stares at the sky. \"What an experience!,\" he says.");
                    enter();
                    System.out.println("\"I will come back stronger than ever. Then, I can kill them. Kill them all!\" ");
                    enter();
                    System.out.println("Millard laughs, but he hears something.");
                    enter();
                    System.out.println("He looks up.");
                    enter();
                    System.out.println("You yell the mighty spell. \"LIGHTNING!\" ");
                    enter();
                    System.out.println("A large lightning bolt comes straight down at Millard.");
                    enter();
                    System.out.println("\"WHAT THE-\" ");
                    enter();
                    System.out.println("The lightning hits Millard and the monster.");
                    enter();
                    System.out.println("Millard becomes charred, then turns to dust.");
                    enter();
                    System.out.println("The wind blows him away.");
                    enter();
                    millard.setHealth(0);
                    millard.printHealth();
                    enter();
                } else if (user.getHeroClass().equals(HeroClass.SWORDSMAN)) {
                    System.out.println("You lift up your Sword.");
                    enter();
                    System.out.println("Everyone is quiet.");
                    enter();
                    System.out.println("You begin to glow. Your Sword turns Blood-Red.");
                    enter();
                    System.out.println("You look at Millard's direction...and aim your Sword.");
                    enter();
                    System.out.println("Millard laughs as he stares at the sky. \"What an experience!,\" he says.");
                    enter();
                    System.out.println("\"I will come back stronger than ever. Then, I can kill them. Kill them all!\" ");
                    enter();
                    System.out.println("Millard laughs, but he hears something.");
                    enter();
                    System.out.println("He turns around.");
                    enter();
                    System.out.println("You yell the Soldier's Chant. \"AERIAL SLICE!\" ");
                    enter();
                    System.out.println("You swing your sword horizontally, creating a red trace to form.");
                    enter();
                    System.out.println("The red line flies toward Millard.");
                    enter();
                    System.out.println("Millard screams.");
                    enter();
                    System.out.println("\"WHAT THE-\" ");
                    enter();
                    System.out.println("The slice hits Millard and the monster.");
                    enter();
                    System.out.println("Millard is still for a second, until he falls off the monster from the waist up.");
                    enter();
                    System.out.println("His bottom half is still on the monster.");
                    enter();
                    System.out.println("Millard falls into the forest. A thud is heard.");
                    enter();
                    millard.setHealth(0);
                    millard.printHealth();
                    enter();
                }
                System.out.println("You take a moment to breath.");
                enter();
                System.out.println("Suddenly, you hear cheering and clapping behind you.");
                enter();
                System.out.println("You turn around and see the townsfolk cheering for you.");
                enter();
                System.out.println("It's a strange feeling. You feel tired, like you're in a dream.");
                enter();
                System.out.println("You realize all your friends are dead, but the townsfolk don't give you a moment to think.");
                enter();
                System.out.println("They pick you up and chant your name.");
                enter();
                if (user.getHeroClass().equals(HeroClass.MAGE)) {
                    System.out.println("\"Everyone cheer for " + n + ", the Mage of Love and Lightning!\" ");
                    enter();
                    System.out.println("Love and Lightning. I guess that's the name now.");
                    enter();
                    System.out.println("You close your eyes to take it all in.");
                    enter();
                    System.out.println("Did I make the right choice? Am I really a hero now?");
                    enter();
                    System.out.println("\"I hope the answer is yes,\" you think to yourself.");
                    enter();
                    user.printAwards(3,"LOVE AND LIGHTNING");
                } else if (user.getHeroClass().equals(HeroClass.SWORDSMAN)) {
                    System.out.println("\"Everyone cheer for " + n + ", the Slayer of Evil!\" ");
                    enter();
                    System.out.println("Slayer of Evil. I guess that's the name now.");
                    enter();
                    System.out.println("You close your eyes to take it all in.");
                    enter();
                    System.out.println("Did I make the right choice? Am I really a hero now?");
                    enter();
                    System.out.println("\"I hope the answer is yes,\" you think to yourself.");
                    enter();
                    user.printAwards(3,"SLAYER OF EVIL");
                } else if (user.getHeroClass().equals(HeroClass.HEALER)) {
                    System.out.println("\"Everyone cheer for " + n + ", the Healer of the World!\" ");
                    enter();
                    System.out.println("Healer of the World. I guess that's the name now.");
                    enter();
                    System.out.println("You close your eyes to take it all in.");
                    enter();
                    System.out.println("Did I make the right choice? Am I really a hero now?");
                    enter();
                    System.out.println("\"I hope the answer is yes,\" you think to yourself.");
                    enter();
                    user.printAwards(3,"HEALER OF THE WORLD");
                }
            } else if (kr.toLowerCase().equals("risk")) {
                if (user.getHeroClass().equals(HeroClass.HEALER)) {
                    System.out.println("");
                    System.out.println("You need to take this risk for your friends.");
                    enter();
                    System.out.println("You take a deep breath.");
                    enter();
                    System.out.println("\"I'm going to die,\" you think to yourself.");
                    enter();
                    System.out.println("You begin to chant.");
                    enter();
                    System.out.println("\"HEAL THE-\" ");
                    enter();
                    System.out.println("Suddenly, you feel someone hold your hand.");
                    enter();
                    System.out.println("You look to your left and see a grandma.");
                    enter();
                    System.out.println("\"It doesn't hurt to rely on others, my boy,\" she says.");
                    enter();
                    System.out.println("She's a healer, too.");
                    enter();
                    System.out.println("You see 10, 15 more mages approach you.");
                    enter();
                    System.out.println("They understand the weight of the spell.");
                    enter();
                    System.out.println("They all smile at you.");
                    enter();
                    System.out.println("A new feeling. What is this feeling?");
                    enter();
                    System.out.println("You all chant at once.");
                    enter();
                    System.out.println("\"HEAL THE WORLD!\" ");
                } else {
                    System.out.println("");
                    System.out.println("You need to take this risk for your friends.");
                    enter();
                    System.out.println("You take a deep breath.");
                    enter();
                    System.out.println("\"I'm going to die,\" you think to yourself.");
                    enter();
                    System.out.println("You start approaching the monsters.");
                    enter();
                    System.out.println("You don't know how you're going to bring back your friends.");
                    enter();
                    System.out.println("Suddenly, you feel someone hold your hand.");
                    enter();
                    System.out.println("You look to your left and see a grandma.");
                    enter();
                    System.out.println("\"It doesn't hurt to rely on others, my boy,\" she says.");
                    enter();
                    System.out.println("She's a healer, too.");
                    enter();
                    System.out.println("You see 10, 15 more mages approach you.");
                    enter();
                    System.out.println("They understand the weight of the spell.");
                    enter();
                    System.out.println("They all smile at you.");
                    enter();
                    System.out.println("A new feeling. What is this feeling?");
                    enter();
                    System.out.println("They chant and begin to glow.");
                    enter();
                    System.out.println("You chant with them, just in case it helps.");
                    enter();
                    System.out.println("\"HEAL THE WORLD!\" ");
                    enter();
                }
                System.out.println("Suddenly, the monsters stop attacking.");
                enter();
                System.out.println("\"What the hell,\" Millard says.");
                enter();
                System.out.println("The monsters slowly change form.");
                enter();
                System.out.println("Magic light swarms around you and travels to every monster.");
                enter();
                System.out.println("They turn back into humans and all the evil magic leaves their body.");
                enter();
                System.out.println("The dark magic swarms into a mist and flies toward it's host, Millard.");
                enter();
                System.out.println("It flies into his body at once. A human cannot handle it, so Millard turns pale.");
                enter();
                System.out.println("\"No! Dammit! Dammit! DAMN YOU, " + n.toUpperCase() + "!\" ");
                enter();
                System.out.println("When the magic disperses, everyone sees Millard. A skeleton of his former self.");
                enter();
                System.out.println("He falls to the ground, turning into dust.");
                enter();
                millard.setHealth(0);
                millard.printHealth();
                enter();
                System.out.println("You take a moment to breath.");
                enter();
                System.out.println("Suddenly, you hear cheering and clapping behind you.");
                enter();
                System.out.println("You turn around and see the townsfolk cheering for you.");
                enter();
                System.out.println("It's a strange feeling. You feel tired, like you're in a dream.");
                enter();
                System.out.println("You and your friends look at one another and hug.");
                enter();
                System.out.println("Your men see you and run towards you.");
                enter();
                System.out.println("\""+ n + "!,\" they yell");
                enter();
                System.out.println("They pick you up and chant your name.");
                enter();
                if (user.getHeroClass().equals(HeroClass.MAGE)) {
                    System.out.println("\"Everyone cheer for " + n + ", the Mage of Love and Lightning!\" ");
                    enter();
                    System.out.println("Love and Lightning. I guess that's the name now.");
                    enter();
                    System.out.println("You close your eyes to take it all in.");
                    enter();
                    System.out.println("Did I make the right choice? Am I really a hero now?");
                    enter();
                    System.out.println("\"I hope the answer is yes,\" you think to yourself.");
                    enter();
                    user.printAwards(4,"LOVE AND LIGHTNING");
                } else if (user.getHeroClass().equals(HeroClass.SWORDSMAN)) {
                    System.out.println("\"Everyone cheer for " + n + ", the Slayer of Evil!\" ");
                    enter();
                    System.out.println("Slayer of Evil. I guess that's the name now.");
                    enter();
                    System.out.println("You close your eyes to take it all in.");
                    enter();
                    System.out.println("Did I make the right choice? Am I really a hero now?");
                    enter();
                    System.out.println("\"I hope the answer is yes,\" you think to yourself.");
                    enter();
                    user.printAwards(4,"SLAYER OF EVIL");
                } else if (user.getHeroClass().equals(HeroClass.HEALER)) {
                    System.out.println("\"Everyone cheer for " + n + ", the Healer of the World!\" ");
                    enter();
                    System.out.println("Healer of the World. I guess that's the name now.");
                    enter();
                    System.out.println("You close your eyes to take it all in.");
                    enter();
                    System.out.println("Did I make the right choice? Am I really a hero now?");
                    enter();
                    System.out.println("\"I hope the answer is yes,\" you think to yourself.");
                    enter();
                    user.printAwards(4,"HEALER OF THE WORLD");
                }
            }
        }
    }
    
    /**
     * This method allows the user to press ENTER when he wants to continue
     * the text.
     *
     */
    public static void enter() {
        System.out.println("");
        try{System.in.read();}
            catch(Exception e){}
    }
}
